### ISSUE TITLE
Deprecated feedstock

### ISSUE THREAD

**Issue by konradha** [conda-forge/jraph-feedstock#4]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running basic examples for Jraph doesn't work as version 0.0.1 uses features deprecated in current JAX, yielding ie.

```bash
AttributeError: module 'jax.tree_util' has no attribute 'tree_multimap'
``` 

Bumping to the current version should do the trick.

### Installed packages

```shell
_libgcc_mutex       0.1         conda_forge          conda-forge
  _openmp_mutex       4.5         2_kmp_llvm           conda-forge
  absl-py             1.4.0       pyhd8ed1ab_0         conda-forge
  brotlipy            0.7.0       py311hd4cff14_1005   conda-forge
  bzip2               1.0.8       h7f98852_4           conda-forge
  c-ares              1.18.1      h7f98852_0           conda-forge
  ca-certificates     2022.12.7   ha878542_0           conda-forge
  certifi             2022.12.7   pyhd8ed1ab_0         conda-forge
  cffi                1.15.1      py311h409f033_3      conda-forge
  charset-normalizer  2.1.1       pyhd8ed1ab_0         conda-forge
  cryptography        40.0.1      py311h9b4c7bb_0      conda-forge
  icu                 72.1        hcb278e6_0           conda-forge
  idna                3.4         pyhd8ed1ab_0         conda-forge
  jax                 0.4.8       pyhd8ed1ab_0         conda-forge
  jaxlib              0.4.7       cpu_py311h9f877bd_0  conda-forge
  ld_impl_linux-64    2.40        h41732ed_0           conda-forge
  libabseil           20230125.0  cxx17_hcb278e6_1     conda-forge
  libblas             3.9.0       16_linux64_openblas  conda-forge
  libcblas            3.9.0       16_linux64_openblas  conda-forge
  libexpat            2.5.0       hcb278e6_1           conda-forge
  libffi              3.4.2       h7f98852_5           conda-forge
  libgcc-ng           12.2.0      h65d4601_19          conda-forge
  libgfortran-ng      12.2.0      h69a702a_19          conda-forge
  libgfortran5        12.2.0      h337968e_19          conda-forge
  libgrpc             1.52.1      hcf146ea_1           conda-forge
  libhwloc            2.9.0       hd6dc26d_0           conda-forge
  libiconv            1.17        h166bdaf_0           conda-forge
  liblapack           3.9.0       16_linux64_openblas  conda-forge
  libnsl              2.0.0       h7f98852_0           conda-forge
  libopenblas         0.3.21      pthreads_h78a6416_3  conda-forge
  libprotobuf         3.21.12     h3eb15da_0           conda-forge
  libsqlite           3.40.0      h753d276_0           conda-forge
  libstdcxx-ng        12.2.0      h46fd767_19          conda-forge
  libuuid             2.38.1      h0b41bf4_0           conda-forge
  libxml2             2.10.3      hfdac1af_6           conda-forge
  libzlib             1.2.13      h166bdaf_4           conda-forge
  llvm-openmp         16.0.0      h417c0b6_0           conda-forge
  mkl                 2022.2.1    h84fe81f_16997       conda-forge
  ml_dtypes           0.0.4       py311h2872171_0      conda-forge
  ncurses             6.3         h27087fc_1           conda-forge
  numpy               1.24.2      py311h8e6699e_0      conda-forge
  openssl             3.1.0       h0b41bf4_0           conda-forge
  opt_einsum          3.3.0       pyhd8ed1ab_1         conda-forge
  packaging           23.0        pyhd8ed1ab_0         conda-forge
  pip                 23.0.1      pyhd8ed1ab_0         conda-forge
  platformdirs        3.2.0       pyhd8ed1ab_0         conda-forge
  pooch               1.7.0       pyha770c72_3         conda-forge
  pycparser           2.21        pyhd8ed1ab_0         conda-forge
  pyopenssl           23.1.1      pyhd8ed1ab_0         conda-forge
  pysocks             1.7.1       pyha2e5f31_6         conda-forge
  python              3.11.1      h2755cc3_0_cpython   conda-forge
  python_abi          3.11        3_cp311              conda-forge
  pytorch             1.13.1      cpu_py311h410fd25_1  conda-forge
  re2                 2023.02.02  hcb278e6_0           conda-forge
  readline            8.2         h8228510_1           conda-forge
  requests            2.28.2      pyhd8ed1ab_0         conda-forge
  scipy               1.10.1      py311h8e6699e_0      conda-forge
  setuptools          67.6.1      pyhd8ed1ab_0         conda-forge
  sleef               3.5.1       h9b69904_2           conda-forge
  tbb                 2021.8.0    hf52228f_0           conda-forge
  tk                  8.6.12      h27826a3_0           conda-forge
  typing-extensions   4.5.0       hd8ed1ab_0           conda-forge
  typing_extensions   4.5.0       pyha770c72_0         conda-forge
  tzdata              2023c       h71feb2d_0           conda-forge
  urllib3             1.26.15     pyhd8ed1ab_0         conda-forge
  wheel               0.40.0      pyhd8ed1ab_0         conda-forge
  xz                  5.2.6       h166bdaf_0           conda-forge
  zlib                1.2.13      h166bdaf_4           conda-forge
  zstd                1.5.2       h3eb15da_6           conda-forge
```

### Environment info

```shell
libmamba version : 0.27.0
     micromamba version : 0.27.0
           curl version : libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5
       virtual packages : __unix=0=0
                          __linux=5.19.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch

               platform : linux-64
```

**Comment by jan-janssen** [comment]
Thanks @konradha, can you provide a quick example that fails for you, then I can add it to the tests.

**Comment by konradha** [comment]
Just copying what Jraph's Quickstart guide has to offer:

```python
import jraph
import jax.numpy as jnp

# Define a three node graph, each node has an integer as its feature.
node_features = jnp.array([[0.], [1.], [2.]])

# We will construct a graph for which there is a directed edge between each node
# and its successor. We define this with `senders` (source nodes) and `receivers`
# (destination nodes).
senders = jnp.array([0, 1, 2])
receivers = jnp.array([1, 2, 0])

# You can optionally add edge attributes.
edges = jnp.array([[5.], [6.], [7.]])

# We then save the number of nodes and the number of edges.
# This information is used to make running GNNs over multiple graphs
# in a GraphsTuple possible.
n_node = jnp.array([3])
n_edge = jnp.array([3])

# Optionally you can add `global` information, such as a graph label.

global_context = jnp.array([[1]])
graph = jraph.GraphsTuple(nodes=node_features, senders=senders, receivers=receivers,
edges=edges, n_node=n_node, n_edge=n_edge, globals=global_context)

two_graph_graphstuple = jraph.batch([graph, graph])
```

yields

```bash
Traceback (most recent call last):
  File "/home/xxx/code/gnn/test_jraph.py", line 28, in <module>
    two_graph_graphstuple = jraph.batch([graph, graph])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/micromamba/envs/gnn/lib/python3.11/site-packages/jraph/_src/utils.py", line 472, in batch
    return _batch(graphs, np_=jnp)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/micromamba/envs/gnn/lib/python3.11/site-packages/jraph/_src/utils.py", line 494, in _batch
    nodes=_map_concat([g.nodes for g in graphs]),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/micromamba/envs/gnn/lib/python3.11/site-packages/jraph/_src/utils.py", line 489, in _map_concat
    return tree.tree_multimap(concat, *nests)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'jax.tree_util' has no attribute 'tree_multimap'
```

which, upon investigation, seems to call a [deleted method](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-16).

**Comment by jan-janssen** [comment]
I added the example as part of the tests in https://github.com/conda-forge/jraph-feedstock/pull/10 and after upgrading to `0.0.6.dev0` everything seems to work just fine. The new version should be available within the next hour.
